name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_get_Q
      id: test_get_q
      uses: education/autograding-command-grader@v1
      with:
        test-name: test_get_Q
        setup-command: sudo -H pip3 install pytest omegaconf dotmap numpy hydra-core
          && sudo -H pip3 install torch --index-url https://download.pytorch.org/whl/cpu
        command: pytest -k test_get_Q
        timeout: 10
        max-score: 10
    - name: test_get_action
      id: test_get_action
      uses: education/autograding-command-grader@v1
      with:
        test-name: test_get_action
        setup-command: ''
        command: pytest -k test_get_action
        timeout: 10
        max-score: 5
    - name: test_get_Q_target
      id: test_get_q_target
      uses: education/autograding-command-grader@v1
      with:
        test-name: test_get_Q_target
        setup-command: ''
        command: pytest -k test_get_Q_target
        timeout: 10
        max-score: 5
    - name: test_get_double_Q_target
      id: test_get_double_q_target
      uses: education/autograding-command-grader@v1
      with:
        test-name: test_get_double_Q_target
        setup-command: ''
        command: pytest -k test_get_double_Q_target
        timeout: 10
        max-score: 5
    - name: test_dueling_forward
      id: test_dueling_forward
      uses: education/autograding-command-grader@v1
      with:
        test-name: test_dueling_forward
        setup-command: ''
        command: pytest -k test_dueling_forward
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST_GET_Q_RESULTS: "${{steps.test_get_q.outputs.result}}"
        TEST_GET_ACTION_RESULTS: "${{steps.test_get_action.outputs.result}}"
        TEST_GET_Q_TARGET_RESULTS: "${{steps.test_get_q_target.outputs.result}}"
        TEST_GET_DOUBLE_Q_TARGET_RESULTS: "${{steps.test_get_double_q_target.outputs.result}}"
        TEST_DUELING_FORWARD_RESULTS: "${{steps.test_dueling_forward.outputs.result}}"
      with:
        runners: test_get_q,test_get_action,test_get_q_target,test_get_double_q_target,test_dueling_forward
