name: drl_hw2
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.2.1
  - pytorch-cuda=12.1 # Comment this line if you are a mac user or want a cpu-only installation
  - pip=23.3.1
  - pip:
    - gymnasium[classic-control]==0.29.1
    - matplotlib
    - hydra-core==1.3.2
    - moviepy==1.0.3
    - dotmap
    - tabulate